/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : MDI
 #	author : miyako
 #	2015/07/10
 #
 # --------------------------------------------------------------------------------*/

#if VERSIONWIN
#include "Shlwapi.h"
#endif

// --- MDI
void MDI_Get_title(sLONG_PTR *pResult, PackagePtr pParams);
void MDI_SET_TITLE(sLONG_PTR *pResult, PackagePtr pParams);
void MDI_USE_ICON_FILE(sLONG_PTR *pResult, PackagePtr pParams);
void MDI_MAXIMIZE(sLONG_PTR *pResult, PackagePtr pParams);
void MDI_MINIMIZE(sLONG_PTR *pResult, PackagePtr pParams);
void MDI_SET_CLOSE_BOX_ENABLED(sLONG_PTR *pResult, PackagePtr pParams);
void MDI_Get_close_box_enabled(sLONG_PTR *pResult, PackagePtr pParams);
void MDI_RESTORE(sLONG_PTR *pResult, PackagePtr pParams);
void MDI_SET_POSITION(sLONG_PTR *pResult, PackagePtr pParams);
void MDI_GET_POSITION(sLONG_PTR *pResult, PackagePtr pParams);
