/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-MDI.h
 #	source generated by 4D Plugin Wizard
 #	Project : MDI
 #	author : miyako
 #	2020/05/29
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_MDI_H
#define PLUGIN_MDI_H

#include "4DPluginAPI.h"

#include "C_LONGINT.h"
#include "C_TEXT.h"

#if VERSIONWIN

#include "shlwapi.h"
#pragma comment(lib, "shlwapi.lib")

#define MESSAGE_TIMEOUT_MS 500

#endif

void MDI_Get_title(PA_PluginParameters params);
void MDI_SET_TITLE(PA_PluginParameters params);
void MDI_USE_ICON_FILE(PA_PluginParameters params);
void MDI_MAXIMIZE(PA_PluginParameters params);
void MDI_MINIMIZE(PA_PluginParameters params);
void MDI_SET_CLOSE_BOX_ENABLED(PA_PluginParameters params);
void MDI_Get_close_box_enabled(PA_PluginParameters params);
void MDI_RESTORE(PA_PluginParameters params);
void MDI_SET_POSITION(PA_PluginParameters params);
void MDI_GET_POSITION(PA_PluginParameters params);

#pragma mark -

#endif /* PLUGIN_MDI_H */
